name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04 # Cambiado a la última versión LTS de Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Run Staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "latest"
          install-go: false
        env:
          STATICCHECK_CACHE: ""

      - name: Run tests
        run: go test ./...

      - name: Semantic Release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
        env:
          DEBUG: "true"
