name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Install dependencies
        run: go mod tidy

      - name: Run Staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "latest"
          install-go: false
        env:
          STATICCHECK_CACHE: ""

      - name: Run tests
        run: go test ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup ko
        uses: ko-build/setup-ko@v0.8

      - name: Build and Push Docker Image with ko
        env:
          KO_DOCKER_REPO: "docker.io/${{ secrets.DOCKER_USERNAME }}"
        run: |
          ko publish --tags "latest,${{ github.sha }}" --platform=linux/amd64,linux/arm64 .

      - name: Run Go Semantic Release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      # Nueva etapa para actualizar el manifiesto
      - name: Checkout cicdfinalgo-argocd repository
        uses: actions/checkout@v3
        with:
          repository: "panrosk/cicdfinalgo-argocd"
          ref: "main"
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Git config
        run: |
          git config --global user.email "oskrf13@gmail.com"
          git config --global user.name "panskrok"

      - name: Update deployment manifest
        run: |
          sed -i "s#image: .*#image: docker.io/${{ secrets.DOCKER_USERNAME }}/final-project:${{ github.sha }}#g" deployment.yml
          git add deployment.yml
          git commit -m "Update deployment image to docker.io/${{ secrets.DOCKER_USERNAME }}/final-project:${{ github.sha }}"

      - name: Push changes
        run: git push origin main
